version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  books-app:
    image: node:latest
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/library
      JWT_SECRET: secret
    volumes:
      - ./backend/app:/app
    working_dir: /app
    command: npm start

  books-frontend:
    image: node:latest
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev
    depends_on:
      - books-app
    environment:
      googleMapKey: "AIzaSyAwkL4wQeTvdZfe0xq16WcniEy15i7V4Pg"
      googleMapId: ea2ec92766f63409
volumes:
  mongo_data:
